name: run-tests

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: 0.12.0
      - name: Run tests
        run: zig build test -- ${{ vars.IPINFO_TOKEN }}